name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.15.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Enable Corepack
      run: corepack enable

    - name: Prepare Yarn 4.1.1
      run: corepack prepare yarn@4.1.1 --activate

    - name: Install dependencies
      run: yarn install --immutable

    - name: Run the tests and generate coverage report
      run: yarn test --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Run linter
      run: yarn lint

    - name: Build
      run: yarn build
